name: pandoc-researchhacking
version: '2.18'
summary: Tool for converting from one markup format to another
description: |
  Pandoc is a Haskell library for converting from one markup format to
  another, and a command-line tool that uses this library.
confinement: strict
grade: stable
base: core20

parts:
  pandoc-researchhacking:
    plugin: dump
    source: https://github.com/jgm/pandoc/releases/download/$SNAPCRAFT_PROJECT_VERSION/pandoc-$SNAPCRAFT_PROJECT_VERSION-linux-$SNAPCRAFT_TARGET_ARCH.tar.gz

apps:
  pandoc:
    command: bin/pandoc
    plugs:
      - home
      - removable-media
